//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blocks
    {
        public int Id { get; set; }
        public int IdTypeBlock { get; set; }
        public Nullable<double> Fullnes { get; set; }
        public Nullable<int> IdAdditionalPad { get; set; }
        public int IdFootbed { get; set; }
        public int HeightBlock { get; set; }
        public int Size { get; set; }
        public bool UseUnuse { get; set; }
        public string CrossReference { get; set; }
    
        public virtual Footbeds Footbed { get; set; }
        public virtual KindOfBlocks KindOfBlock { get; set; }
        public virtual Pads Pad { get; set; }
    }
}
