//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KarmenDbContext : DbContext
    {
        public KarmenDbContext()
            : base("name=KarmenDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blocks> Block { get; set; }
        public virtual DbSet<Colours> Colour { get; set; }
        public virtual DbSet<Components> Component { get; set; }
        public virtual DbSet<Designes> Designe { get; set; }
        public virtual DbSet<Footbeds> Footbed { get; set; }
        public virtual DbSet<Furnitures> Furniture { get; set; }
        public virtual DbSet<KindOfBlocks> KindOfBlock { get; set; }
        public virtual DbSet<KindOfSoles> KindOfSole { get; set; }
        public virtual DbSet<Linings> Lining { get; set; }
        public virtual DbSet<MaterialsOfSole> MaterialOfSole { get; set; }
        public virtual DbSet<Pads> Pad { get; set; }
        public virtual DbSet<Patterns> Pattern { get; set; }
        public virtual DbSet<PhotosOfSole> PhotoOfSole { get; set; }
        public virtual DbSet<ProducedShoes> ProducedShoe { get; set; }
        public virtual DbSet<ShoeModels> ShoeModel { get; set; }
        public virtual DbSet<Soles> Sole { get; set; }
        public virtual DbSet<TopMaterials> TopMaterial { get; set; }
    }
}
