//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoeModels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoeModels()
        {
            this.ProducedShoe = new HashSet<ProducedShoes>();
        }
    
        public int Id { get; set; }
        public int IdTopMaterial { get; set; }
        public int IdDesign { get; set; }
        public int IdSole { get; set; }
        public int IdLining { get; set; }
        public int IdBlock { get; set; }
        public string AdditionalInformation { get; set; }
    
        public virtual Designes Designe { get; set; }
        public virtual Linings Lining { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProducedShoes> ProducedShoe { get; set; }
        public virtual Soles Sole { get; set; }
        public virtual TopMaterials TopMaterial { get; set; }
    }
}
