//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karmen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Component()
        {
            this.KindOfSole = new HashSet<KindOfSole>();
        }
    
        public int Id { get; set; }
        public string TypeOfComponent { get; set; }
        public int IdColour { get; set; }
        public int Size { get; set; }
        public bool UseUnuse { get; set; }
        public string CrossReference { get; set; }
        public string AdditionalInformation { get; set; }
        public Nullable<int> IdMaterilOfCovering { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public string Form { get; set; }
        public string Type { get; set; }
    
        public virtual Colour Colour { get; set; }
        public virtual TopMaterial TopMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KindOfSole> KindOfSole { get; set; }
    }
}
