//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karmen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducedShoe
    {
        public int Id { get; set; }
        public int IdShoeModel { get; set; }
        public string URLPicture { get; set; }
    
        public virtual ShoeModel ShoeModel { get; set; }
    }
}
