//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karmen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoeModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoeModel()
        {
            this.ProducedShoe = new HashSet<ProducedShoe>();
        }
    
        public int Id { get; set; }
        public int IdTopMaterial { get; set; }
        public int IdDesign { get; set; }
        public int IdSole { get; set; }
        public int IdLining { get; set; }
        public int IdBlock { get; set; }
        public string AdditionalInformation { get; set; }
    
        public virtual Designe Designe { get; set; }
        public virtual Lining Lining { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProducedShoe> ProducedShoe { get; set; }
        public virtual Sole Sole { get; set; }
        public virtual TopMaterial TopMaterial { get; set; }
    }
}
